- platform: mqtt
  name: "SONOFF_SUN1"
  command_topic: "cmnd/SONOFF_SUN/POWER1"
  state_topic: "stat/SONOFF_SUN/POWER1"
  optimistic: false
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: true
- platform: mqtt
  name: "SONOFF_SUN2"
  command_topic: "cmnd/SONOFF_SUN/POWER2"
  state_topic: "stat/SONOFF_SUN/POWER2"
  optimistic: false
  payload_on: "ON"
  payload_off: "OFF"
  qos: 1
  retain: true